on:
  workflow_call:
    inputs:
      client-id:
        required: true
        type: string
      tenant-id:
        required: true
        type: string
      subscription-id:
        required: true
        type: string
      staging-registry-name:
        required: true
        type: string
      app-name:
        required: true
        type: string
      docker-build-args:
        required: false
        type: string
        default: ""

#    secrets:
#      envPAT:
#        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          subscription-id: ${{ inputs.subscription-id }}
      - run: |
          az acr login -n ${{ inputs.staging-registry-name }} --subscription ${{ inputs.subscription-id }}
          docker build ${{ inputs.build-args }} -t ${{ inputs.staging-registry-name }}.azurecr.io/${{ inputs.app-name }}:${GITHUB_REF##*/}-${{ github.sha }} .
          docker push ${{ inputs.staging-registry-name }}.azurecr.io/${{ inputs.app-name }}:${GITHUB_REF##*/}-${{ github.sha }}
          docker tag ${{ inputs.staging-registry-name }}.azurecr.io/${{ inputs.app-name }}:${GITHUB_REF##*/}-${{ github.sha }} ${{ inputs.staging-registry-name }}.azurecr.io/${{ inputs.app-name }}:${{ github.sha }}
          docker push ${{ inputs.staging-registry-name }}.azurecr.io/${{ inputs.app-name }}:${{ github.sha }}

